version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: offside-trap-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: offside_trap
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    name: offside-trap-postgres-data